sudo: required
services:
    - docker
    
before_install:
    - docker build -t kepark-dev/docker-react -f  Dockerfile.dev .
    
script:
    - docker run -e CI=true kepark-dev/docker-react npm run test -- --coverage